const a = {
  offset: -1,
  pageNum: 1,
  pageSize: 10,
  recordCount: 333650,
  data: [
    {
      id: "3638364",
      info: {
        regNum: "А8971",
        code: "001А8971",
        divisionParentName:
          "УПРАВЛЕНИЕ ФЕДЕРАЛЬНОЙ СЛУЖБЫ СУДЕБНЫХ ПРИСТАВОВ ПО РЕСПУБЛИКЕ ТЫВА",
        divisionParentCode: "00178511",
        ogrn: "1041700531729",
        fullName:
          "Тере-Хольское районное отделение судебных приставов Управления Федеральной службы судебных приставов по Республике Тыва",
        shortName: "Тере-Хольское РОСП УФССП России по Республике Тыва",
        inn: "1701037522",
        kpp: "171745003",
        regDate: "2014-02-01 00:00:00.0",
        okopfName: "Обособленные подразделения юридических лиц",
        okopfCode: "30003",
        okfsName: "Федеральная собственность",
        okfsCode: "12",
        postIndex: "667903",
        cityType: "",
        cityName: "",
        streetType: "ул",
        streetName: "Молодежная",
        house: "10",
        oktmoName: "с Кунгуртуг",
        oktmoCode: "93643425101",
        orfkName: "Управление Федерального казначейства по Республике Тыва",
        orfkCode: "1200",
        oksmName: "",
        oksmCode: "",
        location: "",
        kbkName: "Федеральная служба судебных приставов",
        kbkCode: "322",
        okoguName: "",
        okoguCode: "",
        okpoCode: "53696533",
        orgTypeName:
          "Федеральный орган государственной власти, федеральный государственный орган, орган государственной власти субъекта Российской Федерации, государственный орган субъекта Российской Федерации, орган местного самоуправления, в том числе его территориальные органы",
        orgTypeCode: "01",
        establishmentKindName: "",
        establishmentKindCode: "",
        legalPersonKindName: "",
        legalPersonKindCode: "",
        ougvName:
          "Обособленное подразделение не является финансовым органом публично-правового образования, органом управления государственными внебюджетным фондом",
        ougvCode: "2",
        uoName: "Федеральная служба судебных приставов",
        uoCode: "00100322",
        creatorKindName: "Российская Федерация",
        creatorKindCode: "10",
        creatorPlaceName: "Российская Федерация",
        creatorPlaceCode: "00000000",
        founderKindName: "",
        founderKindCode: "",
        founderPlaceName: "",
        founderPlaceCode: "",
        budgetLvlName: "Федеральный бюджет",
        budgetLvlCode: "10",
        budgetName: "Федеральный бюджет",
        budgetCode: "99010001",
        statusCode: "1",
        statusName: "действующая",
        regionType: "Респ",
        regionName: "ТЫВА",
        isOGV: "1",
        isObosob: "1",
        orgStatus: "1",
        recordNum: "000000000110А8971041",
        parentCode: "00178511",
        parentName:
          "УПРАВЛЕНИЕ ФЕДЕРАЛЬНОЙ СЛУЖБЫ СУДЕБНЫХ ПРИСТАВОВ ПО РЕСПУБЛИКЕ ТЫВА",
        okatoCode: "",
        okatoName: "",
        guid: "352416B8-90A8-47DA-A695-22AD90EA0994",
        status: "1",
        controlNum: "0",
        bidNum: "1-76-17-000/10865",
        firstRegDate: "2015-09-30 18:25:32.0",
        firstRegGuid: "66f7d528-2552-4b1c-b7a4-060a58a8a41f",
        lastRegGuid: "c5bbd2a3-6f49-438e-90d8-e45e3c573647",
        lastRegDate: "2020-07-13 20:49:18.0",
        lastRegNum: "1-76-00-322/00347",
        updateReason: "D",
        updateNum: "1",
        inclusionDate: "2015-10-01 16:35:15.0",
        exclusionDate: "",
        pubpCode: "",
        rubpCode: "А8971",
        nubpCode: "",
        cpzCode: "",
        pgmyCode: "",
        firmName: "",
        kofkCode: "1200",
        nameDocs: "",
        accMgmt: "",
        naibznachuch: "",
        regionCode: "17",
        areaCode: "",
        areaType: "",
        areaName: "",
        cityCode: "1700000100000",
        localCode: "",
        localName: "Кунгуртуг",
        localType: "с",
        streetCode: "17000001000018000",
        building: "",
        apartment: "",
        reformationDocument: "",
        reformationDocumentNum: "",
        reformationDocumentDate: "",
        reformationName: "",
        reformationCode: "",
        reformationStartDate: "",
        reformationEndDate: "",
        dateUpdate: "2020-07-27 00:00:00.0",
        isExcluded: "0",
        isReorg: "0",
        startDate: "2020-07-16 06:30:59.0",
        endDate: "",
        loadDate: "2020-07-29 10:07:33.0",
        regionKladrCode: "1700000000000",
        egrulnotincluded: "true",
        parentrecordnum: "",
        planningstructuretype: "",
        planningstructurename: "",
        contourTypeCode: "O",
        specEventCode: "",
        speceventcodedop1: "",
        speceventcodedop2: "",
        speceventcodedop3: "",
        dsp: "0",
        ppotypecode: "10",
        ppotypename: "Российская Федерация",
        reforfkCode:
          "/epbs/registry/7710568760-TOFK/data?filtercode=1200&filterstatus=ACTIVE&",
        isUch: "",
      },
      authorities: [],
      activities: [
        {
          activityCode: "84.11.12",
          activityName:
            "Деятельность полномочных представителей Президента Российской Федерации в регионах Российской Федерации и территориальных органов федеральных органов исполнительной власти в субъектах Российской Федерации (республиках, краях, областях)",
          activityKind: "основной",
        },
      ],
      heads: [
        {
          fio: "Казырыкпай Кок-Кыс Алексеевна",
          post: "Начальник отделения- старший судебный пристав",
          docName: "приказ",
          docNum: "488-лс",
          docDate: "2020-05-20 00:00:00.0",
          headMain: "0",
        },
      ],
      successions: [],
      facialAccounts: [
        {
          kindName: "лс для учета операций со СВР",
          kindCode: "05",
          num: "05121А89710",
          createDate: "2014-02-17 00:00:00.0",
          closeDate: "",
          status: "открыт",
          openUfkCode: "1200",
          openUfkName:
            "Управление Федерального казначейства по Республике Тыва",
          openTofkName: "00121124",
          srvUfkCode: "1200",
          srvUfkName: "Управление Федерального казначейства по Республике Тыва",
          accountorgcode: "",
          accountorgfullname: "",
          ppocode: "",
          pponame: "",
          refopenUfkCode:
            "/epbs/registry/7710568760-TOFK/data?filtercode=00121124&filterstatus=ACTIVE&",
          refsrvUfkCode:
            "/epbs/registry/7710568760-TOFK/data?filtercode=-&filterstatus=ACTIVE&",
        },
      ],
      foAccounts: [],
      participantPermissions: [
        {
          name: "Получателя бюджетных средств, осуществляющего операции со средствами во временном распоряжении",
          code: "114",
          startDate: "2015-10-02 00:00:00.0",
          endDate: "",
        },
      ],
      nonParticipantPermissions: [],
      procurementPermissions: [],
      contacts: [
        {
          phone: "8 913 341 25 34; 8 913 341 25 34",
          site: "http://",
          mail: "",
        },
      ],
      acceptAuths: [],
      transfauth: [],
      attachment: [],
      contracts: [],
      ubptransfauthbp: [],
      ubptransfauthbu: [],
      ubpfin: [],
      ksaccounts: [],
    },
    {
      id: "3638446",
      info: {
        regNum: "84831",
        code: "00184831",
        divisionParentName:
          "УПРАВЛЕНИЕ ФЕДЕРАЛЬНОЙ СЛУЖБЫ СУДЕБНЫХ ПРИСТАВОВ ПО ХАНТЫ-МАНСИЙСКОМУ АВТОНОМНОМУ ОКРУГУ - ЮГРЕ",
        divisionParentCode: "00178580",
        ogrn: "1048600010095",
        fullName:
          "Отделение судебных приставов по Октябрьскому району Управления Федеральной службы судебных приставов по Ханты-Мансийскому автономному округу - Югре",
        shortName:
          "ОСП по Октябрьскому району УФССП России по Ханты-Мансийскому автономному округу - Югре",
        inn: "8601024346",
        kpp: "861432001",
        regDate: "2005-01-17 00:00:00.0",
        okopfName: "Обособленные подразделения юридических лиц",
        okopfCode: "30003",
        okfsName: "Федеральная собственность",
        okfsCode: "12",
        postIndex: "628100",
        cityType: "",
        cityName: "",
        streetType: "ул",
        streetName: "Ленина",
        house: "60",
        oktmoName: "пгт Октябрьское",
        oktmoCode: "71821151051",
        orfkName:
          "Управление Федерального казначейства по Ханты-Мансийскому автономному округу - Югре",
        orfkCode: "8700",
        oksmName: "",
        oksmCode: "",
        location: "",
        kbkName: "Федеральная служба судебных приставов",
        kbkCode: "322",
        okoguName: "",
        okoguCode: "",
        okpoCode: "74751041",
        orgTypeName:
          "Федеральный орган государственной власти, федеральный государственный орган, орган государственной власти субъекта Российской Федерации, государственный орган субъекта Российской Федерации, орган местного самоуправления, в том числе его территориальные органы",
        orgTypeCode: "01",
        establishmentKindName: "",
        establishmentKindCode: "",
        legalPersonKindName: "",
        legalPersonKindCode: "",
        ougvName:
          "Обособленное подразделение не является финансовым органом публично-правового образования, органом управления государственными внебюджетным фондом",
        ougvCode: "2",
        uoName: "Федеральная служба судебных приставов",
        uoCode: "00100322",
        creatorKindName: "Российская Федерация",
        creatorKindCode: "10",
        creatorPlaceName: "Российская Федерация",
        creatorPlaceCode: "00000000",
        founderKindName: "",
        founderKindCode: "",
        founderPlaceName: "",
        founderPlaceCode: "",
        budgetLvlName: "Федеральный бюджет",
        budgetLvlCode: "10",
        budgetName: "Федеральный бюджет",
        budgetCode: "99010001",
        statusCode: "1",
        statusName: "действующая",
        regionType: "АО",
        regionName: "ХАНТЫ-МАНСИЙСКИЙ АВТОНОМНЫЙ ОКРУГ - ЮГРА",
        isOGV: "1",
        isObosob: "1",
        orgStatus: "1",
        recordNum: "00000000011084831061",
        parentCode: "00178580",
        parentName:
          "УПРАВЛЕНИЕ ФЕДЕРАЛЬНОЙ СЛУЖБЫ СУДЕБНЫХ ПРИСТАВОВ ПО ХАНТЫ-МАНСИЙСКОМУ АВТОНОМНОМУ ОКРУГУ - ЮГРЕ",
        okatoCode: "",
        okatoName: "",
        guid: "35F9F12E-6709-4F07-8422-5484DD1493D6",
        status: "1",
        controlNum: "0",
        bidNum: "1-76-00-000/13279",
        firstRegDate: "2015-11-27 15:54:56.0",
        firstRegGuid: "11bdee7d-6ad4-49d5-a1cb-29fc6d93a2e4",
        lastRegGuid: "942de9dc-6962-4e60-a20f-bb05cb41ba01",
        lastRegDate: "2020-07-15 17:28:07.0",
        lastRegNum: "1-76-00-322/00530",
        updateReason: "D",
        updateNum: "1",
        inclusionDate: "2015-11-30 10:57:11.0",
        exclusionDate: "",
        pubpCode: "",
        rubpCode: "84831",
        nubpCode: "",
        cpzCode: "",
        pgmyCode: "",
        firmName: "",
        kofkCode: "8700",
        nameDocs: "",
        accMgmt: "",
        naibznachuch: "",
        regionCode: "86",
        areaCode: "",
        areaType: "",
        areaName: "",
        cityCode: "8600000100000",
        localCode: "",
        localName: "Октябрьский",
        localType: "пгт",
        streetCode: "86000001000010600",
        building: "",
        apartment: "",
        reformationDocument: "",
        reformationDocumentNum: "",
        reformationDocumentDate: "",
        reformationName: "",
        reformationCode: "",
        reformationStartDate: "",
        reformationEndDate: "",
        dateUpdate: "2020-07-27 00:00:00.0",
        isExcluded: "0",
        isReorg: "0",
        startDate: "2020-07-17 13:17:18.0",
        endDate: "",
        loadDate: "2020-07-29 10:07:33.0",
        regionKladrCode: "8600000000000",
        egrulnotincluded: "true",
        parentrecordnum: "",
        planningstructuretype: "",
        planningstructurename: "",
        contourTypeCode: "O",
        specEventCode: "",
        speceventcodedop1: "",
        speceventcodedop2: "",
        speceventcodedop3: "",
        dsp: "0",
        ppotypecode: "10",
        ppotypename: "Российская Федерация",
        reforfkCode:
          "/epbs/registry/7710568760-TOFK/data?filtercode=8700&filterstatus=ACTIVE&",
        isUch: "",
      },
      authorities: [],
      activities: [
        {
          activityCode: "84.11.12",
          activityName:
            "Деятельность полномочных представителей Президента Российской Федерации в регионах Российской Федерации и территориальных органов федеральных органов исполнительной власти в субъектах Российской Федерации (республиках, краях, областях)",
          activityKind: "основной",
        },
      ],
      heads: [
        {
          fio: "Меняшкина Альбина Вениаминовна",
          post: "начальник отделения - старший судебный пристав",
          docName: "Приказ",
          docNum: "469-лс",
          docDate: "2020-05-20 00:00:00.0",
          headMain: "0",
        },
      ],
      successions: [],
      facialAccounts: [
        {
          kindName: "лс для учета операций со СВР",
          kindCode: "05",
          num: "05871848310",
          createDate: "2008-12-26 00:00:00.0",
          closeDate: "",
          status: "открыт",
          openUfkCode: "8700",
          openUfkName:
            "Управление Федерального казначейства по Ханты-Мансийскому автономному округу - Югре",
          openTofkName: "00133988",
          srvUfkCode: "8714",
          srvUfkName:
            "Отдел № 4 Управления Федерального казначейства по Ханты-Мансийскому автономному округу - Югре",
          accountorgcode: "",
          accountorgfullname: "",
          ppocode: "",
          pponame: "",
          refopenUfkCode:
            "/epbs/registry/7710568760-TOFK/data?filtercode=00133988&filterstatus=ACTIVE&",
          refsrvUfkCode:
            "/epbs/registry/7710568760-TOFK/data?filtercode=-&filterstatus=ACTIVE&",
        },
      ],
      foAccounts: [],
      participantPermissions: [
        {
          name: "Получателя бюджетных средств, осуществляющего операции со средствами во временном распоряжении",
          code: "114",
          startDate: "2015-11-30 00:00:00.0",
          endDate: "",
        },
      ],
      nonParticipantPermissions: [],
      procurementPermissions: [],
      contacts: [
        {
          phone: "8 346 782 05 97; 8 346 782 05 97",
          site: "http://",
          mail: "",
        },
      ],
      acceptAuths: [],
      transfauth: [],
      attachment: [],
      contracts: [],
      ubptransfauthbp: [],
      ubptransfauthbu: [],
      ubpfin: [],
      ksaccounts: [],
    },
    {
      id: "3638578",
      info: {
        regNum: "84769",
        code: "00184769",
        divisionParentName:
          "УПРАВЛЕНИЕ ФЕДЕРАЛЬНОЙ СЛУЖБЫ СУДЕБНЫХ ПРИСТАВОВ ПО ЯМАЛО-НЕНЕЦКОМУ АВТОНОМНОМУ ОКРУГУ",
        divisionParentCode: "00178583",
        ogrn: "1048900006022",
        fullName:
          "Отделение судебных приставов по г. Муравленко Управления Федеральной службы судебных приставов по Ямало-Ненецкому автономному округу",
        shortName:
          "ОСП по г. Муравленко УФССП России по Ямало-Ненецкому автономному округу",
        inn: "8901016096",
        kpp: "890601001",
        regDate: "2004-12-23 00:00:00.0",
        okopfName: "Обособленные подразделения юридических лиц",
        okopfCode: "30003",
        okfsName: "Федеральная собственность",
        okfsCode: "12",
        postIndex: "629602",
        cityType: "г",
        cityName: "Муравленко",
        streetType: "ул",
        streetName: "Губкина",
        house: "15",
        oktmoName: "г Муравленко",
        oktmoCode: "71955000001",
        orfkName:
          "Управление Федерального казначейства по Ямало-Ненецкому автономному округу",
        orfkCode: "9000",
        oksmName: "",
        oksmCode: "",
        location: "",
        kbkName: "Федеральная служба судебных приставов",
        kbkCode: "322",
        okoguName: "",
        okoguCode: "",
        okpoCode: "74736366",
        orgTypeName:
          "Федеральный орган государственной власти, федеральный государственный орган, орган государственной власти субъекта Российской Федерации, государственный орган субъекта Российской Федерации, орган местного самоуправления, в том числе его территориальные органы",
        orgTypeCode: "01",
        establishmentKindName: "",
        establishmentKindCode: "",
        legalPersonKindName: "",
        legalPersonKindCode: "",
        ougvName:
          "Обособленное подразделение не является финансовым органом публично-правового образования, органом управления государственными внебюджетным фондом",
        ougvCode: "2",
        uoName: "Федеральная служба судебных приставов",
        uoCode: "00100322",
        creatorKindName: "Российская Федерация",
        creatorKindCode: "10",
        creatorPlaceName: "Российская Федерация",
        creatorPlaceCode: "00000000",
        founderKindName: "",
        founderKindCode: "",
        founderPlaceName: "",
        founderPlaceCode: "",
        budgetLvlName: "Федеральный бюджет",
        budgetLvlCode: "10",
        budgetName: "Федеральный бюджет",
        budgetCode: "99010001",
        statusCode: "1",
        statusName: "действующая",
        regionType: "АО",
        regionName: "Ямало-Ненецкий",
        isOGV: "1",
        isObosob: "1",
        orgStatus: "1",
        recordNum: "00000000011084769021",
        parentCode: "00178583",
        parentName:
          "УПРАВЛЕНИЕ ФЕДЕРАЛЬНОЙ СЛУЖБЫ СУДЕБНЫХ ПРИСТАВОВ ПО ЯМАЛО-НЕНЕЦКОМУ АВТОНОМНОМУ ОКРУГУ",
        okatoCode: "",
        okatoName: "",
        guid: "302DF4BE-769A-468E-8512-59A9E7CCA237",
        status: "1",
        controlNum: "0",
        bidNum: "1-76-00-000/13490",
        firstRegDate: "2015-12-03 11:48:15.0",
        firstRegGuid: "48398631-4771-4d9a-b9a1-7e1dc502abaa",
        lastRegGuid: "0c6f972d-c53e-4535-867b-b4b0eafc8a5b",
        lastRegDate: "2020-07-09 18:54:59.0",
        lastRegNum: "1-76-00-322/00289",
        updateReason: "D",
        updateNum: "1",
        inclusionDate: "2015-12-03 14:28:08.0",
        exclusionDate: "",
        pubpCode: "",
        rubpCode: "84769",
        nubpCode: "",
        cpzCode: "",
        pgmyCode: "",
        firmName: "",
        kofkCode: "9000",
        nameDocs: "",
        accMgmt: "",
        naibznachuch: "",
        regionCode: "89",
        areaCode: "",
        areaType: "",
        areaName: "",
        cityCode: "",
        localCode: "",
        localName: "",
        localType: "",
        streetCode: "",
        building: "",
        apartment: "",
        reformationDocument: "",
        reformationDocumentNum: "",
        reformationDocumentDate: "",
        reformationName: "",
        reformationCode: "",
        reformationStartDate: "",
        reformationEndDate: "",
        dateUpdate: "2020-07-27 00:00:00.0",
        isExcluded: "0",
        isReorg: "0",
        startDate: "2020-07-14 14:12:33.0",
        endDate: "",
        loadDate: "2020-07-29 10:07:33.0",
        regionKladrCode: "8900000000000",
        egrulnotincluded: "true",
        parentrecordnum: "",
        planningstructuretype: "",
        planningstructurename: "",
        contourTypeCode: "O",
        specEventCode: "",
        speceventcodedop1: "",
        speceventcodedop2: "",
        speceventcodedop3: "",
        dsp: "0",
        ppotypecode: "10",
        ppotypename: "Российская Федерация",
        reforfkCode:
          "/epbs/registry/7710568760-TOFK/data?filtercode=9000&filterstatus=ACTIVE&",
        isUch: "",
      },
      authorities: [],
      activities: [
        {
          activityCode: "84.11.12",
          activityName:
            "Деятельность полномочных представителей Президента Российской Федерации в регионах Российской Федерации и территориальных органов федеральных органов исполнительной власти в субъектах Российской Федерации (республиках, краях, областях)",
          activityKind: "основной",
        },
      ],
      heads: [
        {
          fio: "Каримова Рима Зинуровна",
          post: 'Начальник отделения " старший судебный пристав',
          docName: "приказ",
          docNum: "424-лс",
          docDate: "2020-05-20 00:00:00.0",
          headMain: "0",
        },
      ],
      successions: [],
      facialAccounts: [
        {
          kindName: "лс для учета операций со СВР",
          kindCode: "05",
          num: "05901847690",
          createDate: "2008-12-31 00:00:00.0",
          closeDate: "",
          status: "открыт",
          openUfkCode: "9000",
          openUfkName:
            "Управление Федерального казначейства по Ямало-Ненецкому автономному округу",
          openTofkName: "00149766",
          srvUfkCode: "9006",
          srvUfkName:
            "Отдел № 6 Управления Федерального казначейства по Ямало-Ненецкому автономному округу",
          accountorgcode: "",
          accountorgfullname: "",
          ppocode: "",
          pponame: "",
          refopenUfkCode:
            "/epbs/registry/7710568760-TOFK/data?filtercode=00149766&filterstatus=ACTIVE&",
          refsrvUfkCode:
            "/epbs/registry/7710568760-TOFK/data?filtercode=-&filterstatus=ACTIVE&",
        },
      ],
      foAccounts: [],
      participantPermissions: [
        {
          name: "Получателя бюджетных средств, осуществляющего операции со средствами во временном распоряжении",
          code: "114",
          startDate: "2015-11-30 00:00:00.0",
          endDate: "",
        },
      ],
      nonParticipantPermissions: [],
      procurementPermissions: [],
      contacts: [
        {
          phone: "8 349 382 77 49; 8 349 382 77 49",
          site: "http://",
          mail: "",
        },
      ],
      acceptAuths: [],
      transfauth: [],
      attachment: [],
      contracts: [],
      ubptransfauthbp: [],
      ubptransfauthbu: [],
      ubpfin: [],
      ksaccounts: [],
    },
    {
      id: "3639292",
      info: {
        regNum: "84943",
        code: "00184943",
        divisionParentName:
          "УПРАВЛЕНИЕ ФЕДЕРАЛЬНОЙ СЛУЖБЫ СУДЕБНЫХ ПРИСТАВОВ ПО РЯЗАНСКОЙ ОБЛАСТИ",
        divisionParentCode: "00178556",
        ogrn: "1056205000026",
        fullName:
          "Отделение судебных приставов по Кадомскому и Ермишинскому районам Управления Федеральной службы судебных приставов по Рязанской области",
        shortName:
          "ОСП по Кадомскому и Ермишинскому районам УФССП России по Рязанской области",
        inn: "6234011182",
        kpp: "620345001",
        regDate: "2014-09-01 00:00:00.0",
        okopfName: "Обособленные подразделения юридических лиц",
        okopfCode: "30003",
        okfsName: "Федеральная собственность",
        okfsCode: "12",
        postIndex: "391670",
        cityType: "",
        cityName: "",
        streetType: "пл",
        streetName: "Красной Армии",
        house: "7",
        oktmoName: "рп Кадом",
        oktmoCode: "61606151051",
        orfkName: "Управление Федерального казначейства по Рязанской области",
        orfkCode: "5900",
        oksmName: "",
        oksmCode: "",
        location: "",
        kbkName: "Федеральная служба судебных приставов",
        kbkCode: "322",
        okoguName: "",
        okoguCode: "",
        okpoCode: "44903720",
        orgTypeName:
          "Федеральный орган государственной власти, федеральный государственный орган, орган государственной власти субъекта Российской Федерации, государственный орган субъекта Российской Федерации, орган местного самоуправления, в том числе его территориальные органы",
        orgTypeCode: "01",
        establishmentKindName: "",
        establishmentKindCode: "",
        legalPersonKindName: "",
        legalPersonKindCode: "",
        ougvName:
          "Обособленное подразделение не является финансовым органом публично-правового образования, органом управления государственными внебюджетным фондом",
        ougvCode: "2",
        uoName: "Федеральная служба судебных приставов",
        uoCode: "00100322",
        creatorKindName: "Российская Федерация",
        creatorKindCode: "10",
        creatorPlaceName: "Российская Федерация",
        creatorPlaceCode: "00000000",
        founderKindName: "",
        founderKindCode: "",
        founderPlaceName: "",
        founderPlaceCode: "",
        budgetLvlName: "Федеральный бюджет",
        budgetLvlCode: "10",
        budgetName: "Федеральный бюджет",
        budgetCode: "99010001",
        statusCode: "1",
        statusName: "действующая",
        regionType: "обл",
        regionName: "РЯЗАНСКАЯ",
        isOGV: "1",
        isObosob: "1",
        orgStatus: "1",
        recordNum: "00000000011084943011",
        parentCode: "00178556",
        parentName:
          "УПРАВЛЕНИЕ ФЕДЕРАЛЬНОЙ СЛУЖБЫ СУДЕБНЫХ ПРИСТАВОВ ПО РЯЗАНСКОЙ ОБЛАСТИ",
        okatoCode: "",
        okatoName: "",
        guid: "402515CE-CD81-476A-8C27-E3C23766BEC9",
        status: "1",
        controlNum: "0",
        bidNum: "1-76-00-000/12808",
        firstRegDate: "2015-11-24 15:30:42.0",
        firstRegGuid: "6af41733-6462-4f52-8fb2-c14d052efbf4",
        lastRegGuid: "b0273694-878c-475a-b744-0ca5a2f87a7b",
        lastRegDate: "2020-07-20 15:31:38.0",
        lastRegNum: "1-76-00-322/00442",
        updateReason: "D",
        updateNum: "1",
        inclusionDate: "2015-11-26 11:28:46.0",
        exclusionDate: "",
        pubpCode: "",
        rubpCode: "84943",
        nubpCode: "",
        cpzCode: "",
        pgmyCode: "",
        firmName: "",
        kofkCode: "5900",
        nameDocs: "",
        accMgmt: "",
        naibznachuch: "",
        regionCode: "62",
        areaCode: "",
        areaType: "",
        areaName: "",
        cityCode: "6200000100000",
        localCode: "",
        localName: "Кадом",
        localType: "рп",
        streetCode: "62000001000020600",
        building: "",
        apartment: "",
        reformationDocument: "",
        reformationDocumentNum: "",
        reformationDocumentDate: "",
        reformationName: "",
        reformationCode: "",
        reformationStartDate: "",
        reformationEndDate: "",
        dateUpdate: "2020-07-27 00:00:00.0",
        isExcluded: "0",
        isReorg: "0",
        startDate: "2020-07-21 10:43:00.0",
        endDate: "",
        loadDate: "2020-07-29 10:07:33.0",
        regionKladrCode: "6200000000000",
        egrulnotincluded: "true",
        parentrecordnum: "",
        planningstructuretype: "",
        planningstructurename: "",
        contourTypeCode: "O",
        specEventCode: "",
        speceventcodedop1: "",
        speceventcodedop2: "",
        speceventcodedop3: "",
        dsp: "0",
        ppotypecode: "10",
        ppotypename: "Российская Федерация",
        reforfkCode:
          "/epbs/registry/7710568760-TOFK/data?filtercode=5900&filterstatus=ACTIVE&",
        isUch: "",
      },
      authorities: [],
      activities: [
        {
          activityCode: "84.11.12",
          activityName:
            "Деятельность полномочных представителей Президента Российской Федерации в регионах Российской Федерации и территориальных органов федеральных органов исполнительной власти в субъектах Российской Федерации (республиках, краях, областях)",
          activityKind: "основной",
        },
      ],
      heads: [
        {
          fio: "Семаева Евгения Евгеньевна",
          post: "Начальник отделения-старший судебный пристав",
          docName: "Приказ",
          docNum: "416-лс",
          docDate: "2020-05-20 00:00:00.0",
          headMain: "0",
        },
      ],
      successions: [],
      facialAccounts: [
        {
          kindName: "лс для учета операций со СВР",
          kindCode: "05",
          num: "05591849430",
          createDate: "2008-12-31 00:00:00.0",
          closeDate: "",
          status: "открыт",
          openUfkCode: "5900",
          openUfkName:
            "Управление Федерального казначейства по Рязанской области",
          openTofkName: "00131164",
          srvUfkCode: "5900",
          srvUfkName:
            "Управление Федерального казначейства по Рязанской области",
          accountorgcode: "",
          accountorgfullname: "",
          ppocode: "",
          pponame: "",
          refopenUfkCode:
            "/epbs/registry/7710568760-TOFK/data?filtercode=00131164&filterstatus=ACTIVE&",
          refsrvUfkCode:
            "/epbs/registry/7710568760-TOFK/data?filtercode=-&filterstatus=ACTIVE&",
        },
      ],
      foAccounts: [],
      participantPermissions: [
        {
          name: "Получателя бюджетных средств, осуществляющего операции со средствами во временном распоряжении",
          code: "114",
          startDate: "2015-11-26 00:00:00.0",
          endDate: "",
        },
      ],
      nonParticipantPermissions: [],
      procurementPermissions: [],
      contacts: [
        {
          phone: "8 491 395 10 52; 8 491 395 10 52",
          site: "http://",
          mail: "",
        },
      ],
      acceptAuths: [],
      transfauth: [],
      attachment: [],
      contracts: [],
      ubptransfauthbp: [],
      ubptransfauthbu: [],
      ubpfin: [],
      ksaccounts: [],
    },
    {
      id: "3639293",
      info: {
        regNum: "Г0008",
        code: "780Г0008",
        divisionParentName: "",
        divisionParentCode: "",
        ogrn: "1167627097340",
        fullName: 'ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "АВТО-РТ"',
        shortName: 'ООО "АВТО-РТ"',
        inn: "7604315366",
        kpp: "760401001",
        regDate: "2016-11-03 00:00:00.0",
        okopfName: "Общества с ограниченной ответственностью",
        okopfCode: "12300",
        okfsName: "Частная собственность",
        okfsCode: "16",
        postIndex: "150001",
        cityType: "ГОРОД",
        cityName: "ЯРОСЛАВЛЬ",
        streetType: "УЛИЦА",
        streetName: "МАЛАЯ ПРОЛЕТАРСКАЯ",
        house: "ДОМ 14",
        oktmoName: "г Ярославль",
        oktmoCode: "78701000001",
        orfkName: "Управление Федерального казначейства по Ярославской области",
        orfkCode: "7100",
        oksmName: "",
        oksmCode: "",
        location: "",
        kbkName: "",
        kbkCode: "",
        okoguName: "",
        okoguCode: "",
        okpoCode: "",
        orgTypeName:
          "Иные юридические лица, иные неучастники бюджетного процесса",
        orgTypeCode: "20",
        establishmentKindName: "",
        establishmentKindCode: "",
        legalPersonKindName: "Создание юридического лица",
        legalPersonKindCode: "11",
        ougvName: "",
        ougvCode: "",
        uoName: "Министерство внутренних дел Российской Федерации",
        uoCode: "00100188",
        creatorKindName: "",
        creatorKindCode: "",
        creatorPlaceName: "",
        creatorPlaceCode: "",
        founderKindName: "",
        founderKindCode: "",
        founderPlaceName: "",
        founderPlaceCode: "",
        budgetLvlName: "Не определен",
        budgetLvlCode: "00",
        budgetName: "",
        budgetCode: "",
        statusCode: "1",
        statusName: "действующая",
        regionType: "ОБЛАСТЬ",
        regionName: "ЯРОСЛАВСКАЯ",
        isOGV: "0",
        isObosob: "0",
        orgStatus: "1",
        recordNum: "787010002000Г0008041",
        parentCode: "",
        parentName: "",
        okatoCode: "",
        okatoName: "",
        guid: "403ADDD0-A0E3-4CF4-9E5C-2CA8CCD4C7BB",
        status: "1",
        controlNum: "0",
        bidNum: "1-76-76-000/00966",
        firstRegDate: "2019-04-03 09:30:45.0",
        firstRegGuid: "cd93ad44-4c21-416a-ab23-26d8a3d0bd5d",
        lastRegGuid: "0107e241-594b-4d3a-8ba8-e66abadb739b",
        lastRegDate: "2020-07-21 16:27:57.0",
        lastRegNum: "1-76-76-000/09815",
        updateReason: "A",
        updateNum: "1",
        inclusionDate: "2019-04-04 10:19:26.0",
        exclusionDate: "",
        pubpCode: "",
        rubpCode: "",
        nubpCode: "",
        cpzCode: "",
        pgmyCode: "",
        firmName: "",
        kofkCode: "7100",
        nameDocs: "",
        accMgmt: "",
        naibznachuch: "",
        regionCode: "76",
        areaCode: "",
        areaType: "",
        areaName: "",
        cityCode: "7600000100000",
        localCode: "",
        localName: "",
        localType: "",
        streetCode: "76000001000043100",
        building: "",
        apartment: "ОФИС 202",
        reformationDocument: "",
        reformationDocumentNum: "",
        reformationDocumentDate: "",
        reformationName: "",
        reformationCode: "",
        reformationStartDate: "",
        reformationEndDate: "",
        dateUpdate: "2020-07-27 00:00:00.0",
        isExcluded: "0",
        isReorg: "0",
        startDate: "2020-07-21 16:27:57.0",
        endDate: "",
        loadDate: "2020-07-29 10:07:33.0",
        regionKladrCode: "7600000000000",
        egrulnotincluded: "false",
        parentrecordnum: "",
        planningstructuretype: "",
        planningstructurename: "",
        contourTypeCode: "O",
        specEventCode: "",
        speceventcodedop1: "",
        speceventcodedop2: "",
        speceventcodedop3: "",
        dsp: "0",
        ppotypecode: "",
        ppotypename: "",
        reforfkCode:
          "/epbs/registry/7710568760-TOFK/data?filtercode=7100&filterstatus=ACTIVE&",
        isUch: "",
      },
      authorities: [],
      activities: [
        {
          activityCode: "45.20",
          activityName:
            "Техническое обслуживание и ремонт автотранспортных средств",
          activityKind: "основной",
        },
        {
          activityCode: "45.31",
          activityName:
            "Торговля оптовая автомобильными деталями, узлами и принадлежностями",
          activityKind: "иной",
        },
        {
          activityCode: "45.32",
          activityName:
            "Торговля розничная автомобильными деталями, узлами и принадлежностями",
          activityKind: "иной",
        },
        {
          activityCode: "46.71",
          activityName:
            "Торговля оптовая твердым, жидким и газообразным топливом и подобными продуктами",
          activityKind: "иной",
        },
      ],
      heads: [
        {
          fio: "Терентьев Сергей Витальевич",
          post: "ДИРЕКТОР",
          docName: "",
          docNum: "",
          docDate: "",
          headMain: "0",
        },
      ],
      successions: [],
      facialAccounts: [
        {
          kindName:
            "л/c для учета операций со средствами юридических лиц при казначейском сопровождении",
          kindCode: "71",
          num: "711Г0008001",
          createDate: "2020-01-21 00:00:00.0",
          closeDate: "",
          status: "открыт",
          openUfkCode: "7200",
          openUfkName:
            "УПРАВЛЕНИЕ ФЕДЕРАЛЬНОГО КАЗНАЧЕЙСТВА ПО Г. САНКТ-ПЕТЕРБУРГУ",
          openTofkName: "00114436",
          srvUfkCode: "7200",
          srvUfkName:
            "УПРАВЛЕНИЕ ФЕДЕРАЛЬНОГО КАЗНАЧЕЙСТВА ПО Г. САНКТ-ПЕТЕРБУРГУ",
          accountorgcode: "",
          accountorgfullname: "",
          ppocode: "",
          pponame: "",
          refopenUfkCode:
            "/epbs/registry/7710568760-TOFK/data?filtercode=00114436&filterstatus=ACTIVE&",
          refsrvUfkCode:
            "/epbs/registry/7710568760-TOFK/data?filtercode=-&filterstatus=ACTIVE&",
        },
        {
          kindName: "л/с для учета операций неучастника бюджетного процесса  ",
          kindCode: "41",
          num: "41716010790",
          createDate: "2019-01-11 00:00:00.0",
          closeDate: "2020-01-20 00:00:00.0",
          status: "закрыт",
          openUfkCode: "7100",
          openUfkName:
            "Управление Федерального казначейства по Ярославской области",
          openTofkName: "00141113",
          srvUfkCode: "7100",
          srvUfkName:
            "Управление Федерального казначейства по Ярославской области",
          accountorgcode: "",
          accountorgfullname: "",
          ppocode: "",
          pponame: "",
          refopenUfkCode:
            "/epbs/registry/7710568760-TOFK/data?filtercode=00141113&filterstatus=ACTIVE&",
          refsrvUfkCode:
            "/epbs/registry/7710568760-TOFK/data?filtercode=-&filterstatus=ACTIVE&",
        },
        {
          kindName: "л/с для учета операций неучастника бюджетного процесса  ",
          kindCode: "41",
          num: "41716010860",
          createDate: "2019-01-18 00:00:00.0",
          closeDate: "2020-01-20 00:00:00.0",
          status: "закрыт",
          openUfkCode: "7100",
          openUfkName:
            "Управление Федерального казначейства по Ярославской области",
          openTofkName: "00141113",
          srvUfkCode: "7100",
          srvUfkName:
            "Управление Федерального казначейства по Ярославской области",
          accountorgcode: "",
          accountorgfullname: "",
          ppocode: "",
          pponame: "",
          refopenUfkCode:
            "/epbs/registry/7710568760-TOFK/data?filtercode=00141113&filterstatus=ACTIVE&",
          refsrvUfkCode:
            "/epbs/registry/7710568760-TOFK/data?filtercode=-&filterstatus=ACTIVE&",
        },
      ],
      foAccounts: [],
      participantPermissions: [],
      nonParticipantPermissions: [
        {
          name: "НУБП",
          registryNum: "Ъ2981",
          code: "303",
          startDate: "2019-04-10 00:00:00.0",
          endDate: "",
          authBudgName: "Федеральный бюджет",
          authBudgCode: "99010001",
          authPPOName: "",
          authPPOCode: "",
          authKBKGlavaName: "Министерство внутренних дел Российской Федерации",
          authKBKGlavaCode: "188",
        },
      ],
      procurementPermissions: [],
      contacts: [
        { phone: "8 485 277 30 71", site: "http://", mail: "tsvyar@mail.ru" },
      ],
      acceptAuths: [],
      transfauth: [],
      attachment: [],
      contracts: [
        {
          contractnumber: "1819188104422007604229808/442",
          signdate: "2018-11-24 00:00:00.0",
          orgcodecontract: "001А8079",
          orgnamecontract:
            'ФЕДЕРАЛЬНОЕ КАЗЕННОЕ УЧРЕЖДЕНИЕ "ЦЕНТР ХОЗЯЙСТВЕННОГО И СЕРВИСНОГО ОБЕСПЕЧЕНИЯ УПРАВЛЕНИЯ МИНИСТЕРСТВА ВНУТРЕННИХ ДЕЛ РОССИЙСКОЙ ФЕДЕРАЦИИ ПО ЯРОСЛАВСКОЙ ОБЛАСТИ"',
          orgcontractbudgetcode: "99010001",
        },
        {
          contractnumber: "191918810006207604229808/6",
          signdate: "2019-01-15 00:00:00.0",
          orgcodecontract: "001А8079",
          orgnamecontract:
            'ФЕДЕРАЛЬНОЕ КАЗЕННОЕ УЧРЕЖДЕНИЕ "ЦЕНТР ХОЗЯЙСТВЕННОГО И СЕРВИСНОГО ОБЕСПЕЧЕНИЯ УПРАВЛЕНИЯ МИНИСТЕРСТВА ВНУТРЕННИХ ДЕЛ РОССИЙСКОЙ ФЕДЕРАЦИИ ПО ЯРОСЛАВСКОЙ ОБЛАСТИ"',
          orgcontractbudgetcode: "99010001",
        },
        {
          contractnumber: "1921188103112007604229808/311",
          signdate: "2019-09-17 00:00:00.0",
          orgcodecontract: "001А8079",
          orgnamecontract:
            'ФЕДЕРАЛЬНОЕ КАЗЕННОЕ УЧРЕЖДЕНИЕ "ЦЕНТР ХОЗЯЙСТВЕННОГО И СЕРВИСНОГО ОБЕСПЕЧЕНИЯ УПРАВЛЕНИЯ МИНИСТЕРСТВА ВНУТРЕННИХ ДЕЛ РОССИЙСКОЙ ФЕДЕРАЦИИ ПО ЯРОСЛАВСКОЙ ОБЛАСТИ"',
          orgcontractbudgetcode: "99010001",
        },
      ],
      ubptransfauthbp: [],
      ubptransfauthbu: [],
      ubpfin: [],
      ksaccounts: [],
    },
    {
      id: "3639762",
      info: {
        regNum: "D0985",
        code: "001D0985",
        divisionParentName:
          "УПРАВЛЕНИЕ ФЕДЕРАЛЬНОЙ СЛУЖБЫ СУДЕБНЫХ ПРИСТАВОВ ПО ТАМБОВСКОЙ ОБЛАСТИ",
        divisionParentCode: "00178562",
        ogrn: "1046882321936",
        fullName:
          "Отделение судебных приставов по взысканию административных штрафов по г. Тамбову и Тамбовскому району Управления Федеральной службы судебных приставов по Тамбовской области",
        shortName:
          "ОСП по ВАШ по г. Тамбову и Тамбовскому району УФССП России по Тамбовской области",
        inn: "6829010040",
        kpp: "682945005",
        regDate: "2016-05-01 00:00:00.0",
        okopfName: "Обособленные подразделения юридических лиц",
        okopfCode: "30003",
        okfsName: "Федеральная собственность",
        okfsCode: "12",
        postIndex: "392000",
        cityType: "г",
        cityName: "Тамбов",
        streetType: "ш",
        streetName: "Моршанское",
        house: "18",
        oktmoName: "г Тамбов",
        oktmoCode: "68701000001",
        orfkName: "Управление Федерального казначейства по Тамбовской области",
        orfkCode: "6400",
        oksmName: "",
        oksmCode: "",
        location: "",
        kbkName: "Федеральная служба судебных приставов",
        kbkCode: "322",
        okoguName: "Федеральная служба судебных приставов",
        okoguCode: "1318025",
        okpoCode: "03297911",
        orgTypeName:
          "Федеральный орган государственной власти, федеральный государственный орган, орган государственной власти субъекта Российской Федерации, государственный орган субъекта Российской Федерации, орган местного самоуправления, в том числе его территориальные органы",
        orgTypeCode: "01",
        establishmentKindName: "",
        establishmentKindCode: "",
        legalPersonKindName: "",
        legalPersonKindCode: "",
        ougvName:
          "Обособленное подразделение не является финансовым органом публично-правового образования, органом управления государственными внебюджетным фондом",
        ougvCode: "2",
        uoName: "Федеральная служба судебных приставов",
        uoCode: "00100322",
        creatorKindName: "Российская Федерация",
        creatorKindCode: "10",
        creatorPlaceName: "Российская Федерация",
        creatorPlaceCode: "00000000",
        founderKindName: "",
        founderKindCode: "",
        founderPlaceName: "",
        founderPlaceCode: "",
        budgetLvlName: "Федеральный бюджет",
        budgetLvlCode: "10",
        budgetName: "Федеральный бюджет",
        budgetCode: "99010001",
        statusCode: "1",
        statusName: "действующая",
        regionType: "ОБЛАСТЬ",
        regionName: "ТАМБОВСКАЯ",
        isOGV: "1",
        isObosob: "1",
        orgStatus: "1",
        recordNum: "000000000110D0985021",
        parentCode: "00178562",
        parentName:
          "УПРАВЛЕНИЕ ФЕДЕРАЛЬНОЙ СЛУЖБЫ СУДЕБНЫХ ПРИСТАВОВ ПО ТАМБОВСКОЙ ОБЛАСТИ",
        okatoCode: "",
        okatoName: "",
        guid: "76F04405-8157-4830-90BE-DD48AFE631D3",
        status: "1",
        controlNum: "0",
        bidNum: "1-76-00-000/00712",
        firstRegDate: "2016-06-06 11:35:01.0",
        firstRegGuid: "565503f9-f0e3-477e-a1f9-f72f4c3fc68e",
        lastRegGuid: "c28438ac-6cab-4a57-b743-8e127c44c72c",
        lastRegDate: "2020-07-21 15:39:31.0",
        lastRegNum: "1-76-00-322/00518",
        updateReason: "D",
        updateNum: "1",
        inclusionDate: "2016-06-07 17:27:01.0",
        exclusionDate: "",
        pubpCode: "",
        rubpCode: "",
        nubpCode: "",
        cpzCode: "",
        pgmyCode: "",
        firmName: "",
        kofkCode: "6400",
        nameDocs: "",
        accMgmt: "",
        naibznachuch: "",
        regionCode: "68",
        areaCode: "",
        areaType: "",
        areaName: "",
        cityCode: "6800000400000",
        localCode: "",
        localName: "",
        localType: "",
        streetCode: "68000004000062600",
        building: "А",
        apartment: "",
        reformationDocument: "",
        reformationDocumentNum: "",
        reformationDocumentDate: "",
        reformationName: "",
        reformationCode: "",
        reformationStartDate: "",
        reformationEndDate: "",
        dateUpdate: "2020-07-27 00:00:00.0",
        isExcluded: "0",
        isReorg: "0",
        startDate: "2020-07-22 17:17:46.0",
        endDate: "",
        loadDate: "2020-07-29 10:07:33.0",
        regionKladrCode: "6800000000000",
        egrulnotincluded: "true",
        parentrecordnum: "",
        planningstructuretype: "",
        planningstructurename: "",
        contourTypeCode: "O",
        specEventCode: "",
        speceventcodedop1: "",
        speceventcodedop2: "",
        speceventcodedop3: "",
        dsp: "0",
        ppotypecode: "10",
        ppotypename: "Российская Федерация",
        reforfkCode:
          "/epbs/registry/7710568760-TOFK/data?filtercode=6400&filterstatus=ACTIVE&",
        isUch: "",
      },
      authorities: [],
      activities: [
        {
          activityCode: "84.11.12",
          activityName:
            "Деятельность полномочных представителей Президента Российской Федерации в регионах Российской Федерации и территориальных органов федеральных органов исполнительной власти в субъектах Российской Федерации (республиках, краях, областях)",
          activityKind: "основной",
        },
        {
          activityCode: "84.11.13",
          activityName:
            "Деятельность территориальных органов федеральных органов исполнительной власти в городах и районах субъектов Российской Федерации",
          activityKind: "иной",
        },
      ],
      heads: [
        {
          fio: "Попова Ольга Анатольевна",
          post: "Врио начальника отделения- старшего судебного пристава",
          docName: "приказ",
          docNum: "8-лс",
          docDate: "2020-06-01 00:00:00.0",
          headMain: "0",
        },
      ],
      successions: [],
      facialAccounts: [
        {
          kindName: "лс для учета операций со СВР",
          kindCode: "05",
          num: "05641D09850",
          createDate: "2016-06-16 00:00:00.0",
          closeDate: "",
          status: "открыт",
          openUfkCode: "6400",
          openUfkName:
            "Управление Федерального казначейства по Тамбовской области",
          openTofkName: "00140376",
          srvUfkCode: "6401",
          srvUfkName:
            "Отдел № 1 Управления Федерального казначейства по Тамбовской области",
          accountorgcode: "",
          accountorgfullname: "",
          ppocode: "",
          pponame: "",
          refopenUfkCode:
            "/epbs/registry/7710568760-TOFK/data?filtercode=00140376&filterstatus=ACTIVE&",
          refsrvUfkCode:
            "/epbs/registry/7710568760-TOFK/data?filtercode=-&filterstatus=ACTIVE&",
        },
      ],
      foAccounts: [],
      participantPermissions: [
        {
          name: "Получателя бюджетных средств, осуществляющего операции со средствами во временном распоряжении",
          code: "114",
          startDate: "2016-06-07 00:00:00.0",
          endDate: "",
        },
      ],
      nonParticipantPermissions: [],
      procurementPermissions: [],
      contacts: [
        {
          phone: "8 475 245 96 42; 8 475 245 96 42",
          site: "http://",
          mail: "",
        },
      ],
      acceptAuths: [],
      transfauth: [],
      attachment: [],
      contracts: [],
      ubptransfauthbp: [],
      ubptransfauthbu: [],
      ubpfin: [],
      ksaccounts: [],
    },
    {
      id: "3638976",
      info: {
        regNum: "83258",
        code: "00183258",
        divisionParentName:
          "УПРАВЛЕНИЕ ФЕДЕРАЛЬНОЙ СЛУЖБЫ СУДЕБНЫХ ПРИСТАВОВ ПО РЕСПУБЛИКЕ МАРИЙ ЭЛ",
        divisionParentCode: "00178506",
        ogrn: "1041200444977",
        fullName:
          "Моркинское районное отделение судебных приставов Управления Федеральной службы судебных приставов по Республике Марий Эл",
        shortName: "Моркинское РОСП УФССП России по Республике Марий Эл",
        inn: "1215099182",
        kpp: "120832001",
        regDate: "2005-01-25 00:00:00.0",
        okopfName: "Обособленные подразделения юридических лиц",
        okopfCode: "30003",
        okfsName: "Федеральная собственность",
        okfsCode: "12",
        postIndex: "425120",
        cityType: "",
        cityName: "",
        streetType: "ул",
        streetName: "Малая Заозерная",
        house: "15",
        oktmoName: "пгт Морки",
        oktmoCode: "88632151051",
        orfkName: "Управление Федерального казначейства по Республике Марий Эл",
        orfkCode: "0800",
        oksmName: "",
        oksmCode: "",
        location: "",
        kbkName: "Федеральная служба судебных приставов",
        kbkCode: "322",
        okoguName: "",
        okoguCode: "",
        okpoCode: "72512817",
        orgTypeName:
          "Федеральный орган государственной власти, федеральный государственный орган, орган государственной власти субъекта Российской Федерации, государственный орган субъекта Российской Федерации, орган местного самоуправления, в том числе его территориальные органы",
        orgTypeCode: "01",
        establishmentKindName: "",
        establishmentKindCode: "",
        legalPersonKindName: "",
        legalPersonKindCode: "",
        ougvName:
          "Обособленное подразделение не является финансовым органом публично-правового образования, органом управления государственными внебюджетным фондом",
        ougvCode: "2",
        uoName: "Федеральная служба судебных приставов",
        uoCode: "00100322",
        creatorKindName: "Российская Федерация",
        creatorKindCode: "10",
        creatorPlaceName: "Российская Федерация",
        creatorPlaceCode: "00000000",
        founderKindName: "",
        founderKindCode: "",
        founderPlaceName: "",
        founderPlaceCode: "",
        budgetLvlName: "Федеральный бюджет",
        budgetLvlCode: "10",
        budgetName: "Федеральный бюджет",
        budgetCode: "99010001",
        statusCode: "1",
        statusName: "действующая",
        regionType: "РЕСПУБЛИКА",
        regionName: "МАРИЙ ЭЛ",
        isOGV: "1",
        isObosob: "1",
        orgStatus: "1",
        recordNum: "00000000011083258021",
        parentCode: "00178506",
        parentName:
          "УПРАВЛЕНИЕ ФЕДЕРАЛЬНОЙ СЛУЖБЫ СУДЕБНЫХ ПРИСТАВОВ ПО РЕСПУБЛИКЕ МАРИЙ ЭЛ",
        okatoCode: "",
        okatoName: "",
        guid: "5713652D-085B-4EF3-8294-3CBB25F86BA8",
        status: "1",
        controlNum: "0",
        bidNum: "1-76-00-322/010641",
        firstRegDate: "2015-09-21 19:06:56.0",
        firstRegGuid: "312e58dd-501a-4607-bf60-ad73ec8c2d5f",
        lastRegGuid: "7700cfa1-56b5-4690-bd1d-cc4195d757c0",
        lastRegDate: "2020-07-10 13:39:55.0",
        lastRegNum: "1-76-00-322/00268",
        updateReason: "D",
        updateNum: "1",
        inclusionDate: "2015-09-30 19:00:09.0",
        exclusionDate: "",
        pubpCode: "",
        rubpCode: "83258",
        nubpCode: "",
        cpzCode: "01081000061",
        pgmyCode: "",
        firmName: "",
        kofkCode: "0800",
        nameDocs: "",
        accMgmt: "",
        naibznachuch: "",
        regionCode: "12",
        areaCode: "",
        areaType: "",
        areaName: "",
        cityCode: "1200000100000",
        localCode: "",
        localName: "Морки",
        localType: "пгт",
        streetCode: "12000001000008300",
        building: "",
        apartment: "",
        reformationDocument: "",
        reformationDocumentNum: "",
        reformationDocumentDate: "",
        reformationName: "",
        reformationCode: "",
        reformationStartDate: "",
        reformationEndDate: "",
        dateUpdate: "2020-07-27 00:00:00.0",
        isExcluded: "0",
        isReorg: "0",
        startDate: "2020-07-14 18:16:23.0",
        endDate: "",
        loadDate: "2020-07-29 10:07:33.0",
        regionKladrCode: "1200000000000",
        egrulnotincluded: "true",
        parentrecordnum: "",
        planningstructuretype: "",
        planningstructurename: "",
        contourTypeCode: "O",
        specEventCode: "",
        speceventcodedop1: "",
        speceventcodedop2: "",
        speceventcodedop3: "",
        dsp: "0",
        ppotypecode: "10",
        ppotypename: "Российская Федерация",
        reforfkCode:
          "/epbs/registry/7710568760-TOFK/data?filtercode=0800&filterstatus=ACTIVE&",
        isUch: "",
      },
      authorities: [],
      activities: [
        {
          activityCode: "84.11.12",
          activityName:
            "Деятельность полномочных представителей Президента Российской Федерации в регионах Российской Федерации и территориальных органов федеральных органов исполнительной власти в субъектах Российской Федерации (республиках, краях, областях)",
          activityKind: "основной",
        },
      ],
      heads: [
        {
          fio: "Муравьева Наталья Васильевна",
          post: "Начальник отделения-старший судебный пристав",
          docName: "приказ",
          docNum: "455-лс",
          docDate: "2020-05-20 00:00:00.0",
          headMain: "0",
        },
      ],
      successions: [],
      facialAccounts: [
        {
          kindName: "лс для учета операций со СВР",
          kindCode: "05",
          num: "05081832580",
          createDate: "2008-12-30 00:00:00.0",
          closeDate: "",
          status: "открыт",
          openUfkCode: "0800",
          openUfkName:
            "Управление Федерального казначейства по Республике Марий Эл",
          openTofkName: "00132228",
          srvUfkCode: "0800",
          srvUfkName:
            "Управление Федерального казначейства по Республике Марий Эл",
          accountorgcode: "",
          accountorgfullname: "",
          ppocode: "",
          pponame: "",
          refopenUfkCode:
            "/epbs/registry/7710568760-TOFK/data?filtercode=00132228&filterstatus=ACTIVE&",
          refsrvUfkCode:
            "/epbs/registry/7710568760-TOFK/data?filtercode=-&filterstatus=ACTIVE&",
        },
      ],
      foAccounts: [],
      participantPermissions: [
        {
          name: "Получателя бюджетных средств, осуществляющего операции со средствами во временном распоряжении",
          code: "114",
          startDate: "2015-09-28 00:00:00.0",
          endDate: "",
        },
      ],
      nonParticipantPermissions: [],
      procurementPermissions: [],
      contacts: [
        {
          phone: "8 836 359 12 10; 8 836 359 12 10",
          site: "http://",
          mail: "",
        },
      ],
      acceptAuths: [],
      transfauth: [],
      attachment: [],
      contracts: [],
      ubptransfauthbp: [],
      ubptransfauthbu: [],
      ubpfin: [],
      ksaccounts: [],
    },
    {
      id: "3639456",
      info: {
        regNum: "84838",
        code: "00184838",
        divisionParentName:
          "УПРАВЛЕНИЕ ФЕДЕРАЛЬНОЙ СЛУЖБЫ СУДЕБНЫХ ПРИСТАВОВ ПО ХАНТЫ-МАНСИЙСКОМУ АВТОНОМНОМУ ОКРУГУ - ЮГРЕ",
        divisionParentCode: "00178580",
        ogrn: "1048600010095",
        fullName:
          "Отделение судебных приставов по г. Ураю Управления Федеральной службы судебных приставов по Ханты-Мансийскому автономному округу - Югре",
        shortName:
          "ОСП по г. Ураю УФССП России по Ханты-Мансийскому автономному округу - Югре",
        inn: "8601024346",
        kpp: "860603001",
        regDate: "2005-01-18 00:00:00.0",
        okopfName: "Обособленные подразделения юридических лиц",
        okopfCode: "30003",
        okfsName: "Федеральная собственность",
        okfsCode: "12",
        postIndex: "628285",
        cityType: "г",
        cityName: "Урай",
        streetType: "ул",
        streetName: "2-й мкр",
        house: '89 "А"',
        oktmoName: "г Урай",
        oktmoCode: "71878000001",
        orfkName:
          "Управление Федерального казначейства по Ханты-Мансийскому автономному округу - Югре",
        orfkCode: "8700",
        oksmName: "",
        oksmCode: "",
        location: "",
        kbkName: "Федеральная служба судебных приставов",
        kbkCode: "322",
        okoguName: "",
        okoguCode: "",
        okpoCode: "74751041",
        orgTypeName:
          "Федеральный орган государственной власти, федеральный государственный орган, орган государственной власти субъекта Российской Федерации, государственный орган субъекта Российской Федерации, орган местного самоуправления, в том числе его территориальные органы",
        orgTypeCode: "01",
        establishmentKindName: "",
        establishmentKindCode: "",
        legalPersonKindName: "",
        legalPersonKindCode: "",
        ougvName:
          "Обособленное подразделение не является финансовым органом публично-правового образования, органом управления государственными внебюджетным фондом",
        ougvCode: "2",
        uoName: "Федеральная служба судебных приставов",
        uoCode: "00100322",
        creatorKindName: "Российская Федерация",
        creatorKindCode: "10",
        creatorPlaceName: "Российская Федерация",
        creatorPlaceCode: "00000000",
        founderKindName: "",
        founderKindCode: "",
        founderPlaceName: "",
        founderPlaceCode: "",
        budgetLvlName: "Федеральный бюджет",
        budgetLvlCode: "10",
        budgetName: "Федеральный бюджет",
        budgetCode: "99010001",
        statusCode: "1",
        statusName: "действующая",
        regionType: "АО",
        regionName: "ХАНТЫ-МАНСИЙСКИЙ АВТОНОМНЫЙ ОКРУГ - ЮГРА",
        isOGV: "1",
        isObosob: "1",
        orgStatus: "1",
        recordNum: "00000000011084838091",
        parentCode: "00178580",
        parentName:
          "УПРАВЛЕНИЕ ФЕДЕРАЛЬНОЙ СЛУЖБЫ СУДЕБНЫХ ПРИСТАВОВ ПО ХАНТЫ-МАНСИЙСКОМУ АВТОНОМНОМУ ОКРУГУ - ЮГРЕ",
        okatoCode: "",
        okatoName: "",
        guid: "3E550CBB-ED15-4508-BD4C-31995DBE37BF",
        status: "1",
        controlNum: "0",
        bidNum: "1-76-00-000/13286",
        firstRegDate: "2015-11-27 16:17:46.0",
        firstRegGuid: "1504a73e-7225-443b-b2af-b8891a9d47f3",
        lastRegGuid: "a037a43b-8524-4cd2-bc8c-537e08800c99",
        lastRegDate: "2020-07-22 16:20:21.0",
        lastRegNum: "1-76-00-322/00572",
        updateReason: "D",
        updateNum: "1",
        inclusionDate: "2015-11-30 15:55:57.0",
        exclusionDate: "",
        pubpCode: "",
        rubpCode: "84838",
        nubpCode: "",
        cpzCode: "",
        pgmyCode: "",
        firmName: "",
        kofkCode: "8700",
        nameDocs: "",
        accMgmt: "",
        naibznachuch: "",
        regionCode: "86",
        areaCode: "",
        areaType: "",
        areaName: "",
        cityCode: "8600000100000",
        localCode: "",
        localName: "",
        localType: "",
        streetCode: "86000001000010600",
        building: "",
        apartment: "",
        reformationDocument: "",
        reformationDocumentNum: "",
        reformationDocumentDate: "",
        reformationName: "",
        reformationCode: "",
        reformationStartDate: "",
        reformationEndDate: "",
        dateUpdate: "2020-07-27 00:00:00.0",
        isExcluded: "0",
        isReorg: "0",
        startDate: "2020-07-24 16:28:45.0",
        endDate: "",
        loadDate: "2020-07-29 10:07:33.0",
        regionKladrCode: "8600000000000",
        egrulnotincluded: "true",
        parentrecordnum: "",
        planningstructuretype: "",
        planningstructurename: "",
        contourTypeCode: "O",
        specEventCode: "",
        speceventcodedop1: "",
        speceventcodedop2: "",
        speceventcodedop3: "",
        dsp: "0",
        ppotypecode: "10",
        ppotypename: "Российская Федерация",
        reforfkCode:
          "/epbs/registry/7710568760-TOFK/data?filtercode=8700&filterstatus=ACTIVE&",
        isUch: "",
      },
      authorities: [],
      activities: [
        {
          activityCode: "84.11.12",
          activityName:
            "Деятельность полномочных представителей Президента Российской Федерации в регионах Российской Федерации и территориальных органов федеральных органов исполнительной власти в субъектах Российской Федерации (республиках, краях, областях)",
          activityKind: "основной",
        },
      ],
      heads: [
        {
          fio: "Головизнина Жанна Геннадиевна",
          post: "начальник отделения - старший судебный пристав",
          docName: "Приказ",
          docNum: "469-лс",
          docDate: "2020-05-20 00:00:00.0",
          headMain: "0",
        },
      ],
      successions: [],
      facialAccounts: [
        {
          kindName: "лс для учета операций со СВР",
          kindCode: "05",
          num: "05871848380",
          createDate: "2008-12-31 00:00:00.0",
          closeDate: "",
          status: "открыт",
          openUfkCode: "8700",
          openUfkName:
            "Управление Федерального казначейства по Ханты-Мансийскому автономному округу - Югре",
          openTofkName: "00133988",
          srvUfkCode: "8706",
          srvUfkName:
            "Отдел № 7 Управления Федерального казначейства по Ханты-Мансийскому автономному округу - Югре",
          accountorgcode: "",
          accountorgfullname: "",
          ppocode: "",
          pponame: "",
          refopenUfkCode:
            "/epbs/registry/7710568760-TOFK/data?filtercode=00133988&filterstatus=ACTIVE&",
          refsrvUfkCode:
            "/epbs/registry/7710568760-TOFK/data?filtercode=-&filterstatus=ACTIVE&",
        },
      ],
      foAccounts: [],
      participantPermissions: [
        {
          name: "Получателя бюджетных средств, осуществляющего операции со средствами во временном распоряжении",
          code: "114",
          startDate: "2015-11-30 00:00:00.0",
          endDate: "",
        },
      ],
      nonParticipantPermissions: [],
      procurementPermissions: [],
      contacts: [
        {
          phone: "8 346 673 43 33; 8 346 673 43 33",
          site: "http://",
          mail: "",
        },
      ],
      acceptAuths: [],
      transfauth: [],
      attachment: [],
      contracts: [],
      ubptransfauthbp: [],
      ubptransfauthbu: [],
      ubpfin: [],
      ksaccounts: [],
    },
    {
      id: "3639459",
      info: {
        regNum: "А9633",
        code: "001А9633",
        divisionParentName:
          "УПРАВЛЕНИЕ ФЕДЕРАЛЬНОЙ СЛУЖБЫ СУДЕБНЫХ ПРИСТАВОВ ПО ТАМБОВСКОЙ ОБЛАСТИ",
        divisionParentCode: "00178562",
        ogrn: "1046882321936",
        fullName:
          "Отделение судебных приставов по Рассказовскому и Бондарскому районам Управления Федеральной службы судебных приставов по Тамбовской области",
        shortName:
          "ОСП по Рассказовскому и Бондарскому районам УФССП России по Тамбовской области",
        inn: "6829010040",
        kpp: "682803001",
        regDate: "2005-03-23 00:00:00.0",
        okopfName: "Обособленные подразделения юридических лиц",
        okopfCode: "30003",
        okfsName: "Федеральная собственность",
        okfsCode: "12",
        postIndex: "393250",
        cityType: "г",
        cityName: "Рассказово",
        streetType: "ул",
        streetName: "Советская",
        house: "6",
        oktmoName: "г Рассказово",
        oktmoCode: "68725000001",
        orfkName: "Управление Федерального казначейства по Тамбовской области",
        orfkCode: "6400",
        oksmName: "",
        oksmCode: "",
        location: "",
        kbkName: "Федеральная служба судебных приставов",
        kbkCode: "322",
        okoguName: "",
        okoguCode: "",
        okpoCode: "03300234",
        orgTypeName:
          "Федеральный орган государственной власти, федеральный государственный орган, орган государственной власти субъекта Российской Федерации, государственный орган субъекта Российской Федерации, орган местного самоуправления, в том числе его территориальные органы",
        orgTypeCode: "01",
        establishmentKindName: "",
        establishmentKindCode: "",
        legalPersonKindName: "",
        legalPersonKindCode: "",
        ougvName:
          "Обособленное подразделение не является финансовым органом публично-правового образования, органом управления государственными внебюджетным фондом",
        ougvCode: "2",
        uoName: "Федеральная служба судебных приставов",
        uoCode: "00100322",
        creatorKindName: "Российская Федерация",
        creatorKindCode: "10",
        creatorPlaceName: "Российская Федерация",
        creatorPlaceCode: "00000000",
        founderKindName: "",
        founderKindCode: "",
        founderPlaceName: "",
        founderPlaceCode: "",
        budgetLvlName: "Федеральный бюджет",
        budgetLvlCode: "10",
        budgetName: "Федеральный бюджет",
        budgetCode: "99010001",
        statusCode: "1",
        statusName: "действующая",
        regionType: "обл",
        regionName: "Тамбовская",
        isOGV: "1",
        isObosob: "1",
        orgStatus: "1",
        recordNum: "000000000110А9633021",
        parentCode: "00178562",
        parentName:
          "УПРАВЛЕНИЕ ФЕДЕРАЛЬНОЙ СЛУЖБЫ СУДЕБНЫХ ПРИСТАВОВ ПО ТАМБОВСКОЙ ОБЛАСТИ",
        okatoCode: "",
        okatoName: "",
        guid: "3EA1E517-5FED-472A-B1E0-96112A5916C8",
        status: "1",
        controlNum: "0",
        bidNum: "1-76-00-000/13046",
        firstRegDate: "2015-11-26 12:26:59.0",
        firstRegGuid: "c34de05b-f2f3-486b-b6cc-cae2e1ca5d04",
        lastRegGuid: "2186a9bd-4382-48e2-b476-2f747e6e313c",
        lastRegDate: "2020-07-21 15:59:37.0",
        lastRegNum: "1-76-00-322/00521",
        updateReason: "D",
        updateNum: "1",
        inclusionDate: "2015-11-27 13:49:10.0",
        exclusionDate: "",
        pubpCode: "",
        rubpCode: "А9633",
        nubpCode: "",
        cpzCode: "",
        pgmyCode: "",
        firmName: "",
        kofkCode: "6400",
        nameDocs: "",
        accMgmt: "",
        naibznachuch: "",
        regionCode: "68",
        areaCode: "",
        areaType: "",
        areaName: "",
        cityCode: "6800000400000",
        localCode: "",
        localName: "",
        localType: "",
        streetCode: "68000004000062600",
        building: "",
        apartment: "",
        reformationDocument: "",
        reformationDocumentNum: "",
        reformationDocumentDate: "",
        reformationName: "",
        reformationCode: "",
        reformationStartDate: "",
        reformationEndDate: "",
        dateUpdate: "2020-07-27 00:00:00.0",
        isExcluded: "0",
        isReorg: "0",
        startDate: "2020-07-22 16:43:10.0",
        endDate: "",
        loadDate: "2020-07-29 10:07:33.0",
        regionKladrCode: "6800000000000",
        egrulnotincluded: "true",
        parentrecordnum: "",
        planningstructuretype: "",
        planningstructurename: "",
        contourTypeCode: "O",
        specEventCode: "",
        speceventcodedop1: "",
        speceventcodedop2: "",
        speceventcodedop3: "",
        dsp: "0",
        ppotypecode: "10",
        ppotypename: "Российская Федерация",
        reforfkCode:
          "/epbs/registry/7710568760-TOFK/data?filtercode=6400&filterstatus=ACTIVE&",
        isUch: "",
      },
      authorities: [],
      activities: [
        {
          activityCode: "84.11.12",
          activityName:
            "Деятельность полномочных представителей Президента Российской Федерации в регионах Российской Федерации и территориальных органов федеральных органов исполнительной власти в субъектах Российской Федерации (республиках, краях, областях)",
          activityKind: "основной",
        },
        {
          activityCode: "84.11.13",
          activityName:
            "Деятельность территориальных органов федеральных органов исполнительной власти в городах и районах субъектов Российской Федерации",
          activityKind: "иной",
        },
      ],
      heads: [
        {
          fio: "Поликанова Оксана Ивановна",
          post: "начальник отделения-старший судебный пристав",
          docName: "приказ",
          docNum: "453-лс",
          docDate: "2020-05-20 00:00:00.0",
          headMain: "0",
        },
      ],
      successions: [],
      facialAccounts: [
        {
          kindName: "лс для учета операций со СВР",
          kindCode: "05",
          num: "05641А96330",
          createDate: "2015-02-25 00:00:00.0",
          closeDate: "",
          status: "открыт",
          openUfkCode: "6400",
          openUfkName:
            "Управление Федерального казначейства по Тамбовской области",
          openTofkName: "00140376",
          srvUfkCode: "6417",
          srvUfkName:
            "Отдел № 17 Управления Федерального казначейства по Тамбовской области",
          accountorgcode: "",
          accountorgfullname: "",
          ppocode: "",
          pponame: "",
          refopenUfkCode:
            "/epbs/registry/7710568760-TOFK/data?filtercode=00140376&filterstatus=ACTIVE&",
          refsrvUfkCode:
            "/epbs/registry/7710568760-TOFK/data?filtercode=-&filterstatus=ACTIVE&",
        },
      ],
      foAccounts: [],
      participantPermissions: [
        {
          name: "Получателя бюджетных средств, осуществляющего операции со средствами во временном распоряжении",
          code: "114",
          startDate: "2015-11-27 00:00:00.0",
          endDate: "",
        },
      ],
      nonParticipantPermissions: [],
      procurementPermissions: [],
      contacts: [
        {
          phone: "8 475 313 37 06; 8 475 313 37 06",
          site: "http://",
          mail: "",
        },
      ],
      acceptAuths: [],
      transfauth: [],
      attachment: [],
      contracts: [],
      ubptransfauthbp: [],
      ubptransfauthbu: [],
      ubpfin: [],
      ksaccounts: [],
    },
    {
      id: "3639621",
      info: {
        regNum: "20418",
        code: "41220418",
        divisionParentName: "",
        divisionParentCode: "",
        ogrn: "1144703002113",
        fullName:
          "УПОЛНОМОЧЕННЫЙ ПО ЗАЩИТЕ ПРАВ ПРЕДПРИНИМАТЕЛЕЙ В ЛЕНИНГРАДСКОЙ ОБЛАСТИ",
        shortName:
          "УПОЛНОМОЧЕННЫЙ ПО ЗАЩИТЕ ПРАВ ПРЕДПРИНИМАТЕЛЕЙ В ЛЕНИНГРАДСКОЙ ОБЛАСТИ",
        inn: "4703140560",
        kpp: "470301001",
        regDate: "2014-06-18 00:00:00.0",
        okopfName:
          "Государственные казенные учреждения субъектов Российской Федерации",
        okopfCode: "75204",
        okfsName: "Собственность субъектов Российской Федерации",
        okfsCode: "13",
        postIndex: "188643",
        cityType: "Г",
        cityName: "ВСЕВОЛОЖСК",
        streetType: "Ш",
        streetName: "КОЛТУШСКОЕ",
        house: "138",
        oktmoName: "г Всеволожск",
        oktmoCode: "41612101001",
        orfkName:
          "Управление Федерального казначейства по Ленинградской области",
        orfkCode: "4500",
        oksmName: "",
        oksmCode: "",
        location: "",
        kbkName:
          "УПОЛНОМОЧЕННЫЙ ПО ЗАЩИТЕ ПРАВ ПРЕДПРИНИМАТЕЛЕЙ В ЛЕНИНГРАДСКОЙ ОБЛАСТИ",
        kbkCode: "949",
        okoguName:
          "Уполномоченные по правам человека субъектов Российской Федерации",
        okoguCode: "2500030",
        okpoCode: "25839100",
        orgTypeName:
          "Федеральный орган государственной власти, федеральный государственный орган, орган государственной власти субъекта Российской Федерации, государственный орган субъекта Российской Федерации, орган местного самоуправления, в том числе его территориальные органы",
        orgTypeCode: "01",
        establishmentKindName: "",
        establishmentKindCode: "",
        legalPersonKindName: "Создание юридического лица",
        legalPersonKindCode: "11",
        ougvName:
          "Организация не является финансовым органом публично-правового образования, органом управления государственными внебюджетным фондом",
        ougvCode: "2",
        uoName: "Комитет финансов Ленинградской области",
        uoCode: "40200015",
        creatorKindName: "Субъект Российской Федерации",
        creatorKindCode: "20",
        creatorPlaceName: "Ленинградская область",
        creatorPlaceCode: "41000000",
        founderKindName: "",
        founderKindCode: "",
        founderPlaceName: "",
        founderPlaceCode: "",
        budgetLvlName: "Бюджет субъекта Российской Федерации",
        budgetLvlCode: "20",
        budgetName: "Областной бюджет Ленинградской области",
        budgetCode: "45020238",
        statusCode: "1",
        statusName: "действующая",
        regionType: "ОБЛ",
        regionName: "ЛЕНИНГРАДСКАЯ",
        isOGV: "1",
        isObosob: "0",
        orgStatus: "1",
        recordNum: "41000000012020418041",
        parentCode: "",
        parentName: "",
        okatoCode: "",
        okatoName: "",
        guid: "75347084-D4FE-425F-9363-612F2E262E72",
        status: "1",
        controlNum: "0",
        bidNum: "1-76-47-949/00199",
        firstRegDate: "2015-10-02 12:35:23.0",
        firstRegGuid: "97d8732b-9c99-4323-a24f-d824d55106d4",
        lastRegGuid: "88fb4987-7b87-43b9-bff9-49b56dfbc065",
        lastRegDate: "2020-07-17 15:00:07.0",
        lastRegNum: "1-76-47-949/390454",
        updateReason: "A",
        updateNum: "1",
        inclusionDate: "2015-10-02 15:32:00.0",
        exclusionDate: "",
        pubpCode: "20418",
        rubpCode: "",
        nubpCode: "",
        cpzCode: "01452000041",
        pgmyCode: "",
        firmName: "",
        kofkCode: "",
        nameDocs:
          "УПОЛНОМОЧЕННЫЙ ПО ЗАЩИТЕ ПРАВ ПРЕДПРИНИМАТЕЛЕЙ В ЛЕНИНГРАДСКОЙ ОБЛАСТИ",
        accMgmt: "",
        naibznachuch: "",
        regionCode: "47",
        areaCode: "4700500000000",
        areaType: "Р-Н",
        areaName: "ВСЕВОЛОЖСКИЙ",
        cityCode: "4700500100000",
        localCode: "",
        localName: "",
        localType: "",
        streetCode: "47005001000006600",
        building: "",
        apartment: "",
        reformationDocument: "",
        reformationDocumentNum: "",
        reformationDocumentDate: "",
        reformationName: "",
        reformationCode: "",
        reformationStartDate: "",
        reformationEndDate: "",
        dateUpdate: "2024-06-11 11:46:07.0",
        isExcluded: "0",
        isReorg: "0",
        startDate: "2020-07-17 15:00:07.0",
        endDate: "",
        loadDate: "2024-06-11 13:03:07.0",
        regionKladrCode: "4700000000000",
        egrulnotincluded: "false",
        parentrecordnum: "",
        planningstructuretype: "",
        planningstructurename: "",
        contourTypeCode: "O",
        specEventCode: "",
        speceventcodedop1: "",
        speceventcodedop2: "",
        speceventcodedop3: "",
        dsp: "",
        ppotypecode: "20",
        ppotypename: "Субъект Российской Федерации",
        reforfkCode:
          "/epbs/registry/7710568760-TOFK/data?filtercode=4500&filterstatus=ACTIVE&",
        isUch: "",
      },
      authorities: [],
      activities: [
        {
          activityCode: "84.11.2",
          activityName:
            "Деятельность органов государственной власти по управлению вопросами общего характера, кроме судебной власти, субъектов Российской Федерации",
          activityKind: "основной",
        },
      ],
      heads: [
        {
          fio: "РУЛЕВА ЕЛЕНА АЛЕКСАНДРОВНА",
          post: "УПОЛНОМОЧЕННЫЙ ПО ЗАЩИТЕ ПРАВ ПРЕДПРИНИМАТЕЛЕЙ В ЛЕНИНГРАДСКОЙ ОБЛАСТИ",
          docName: "Постановление",
          docNum: "551",
          docDate: "2014-05-28 00:00:00.0",
          headMain: "0",
        },
      ],
      successions: [],
      facialAccounts: [
        {
          kindName: "лс АДБ",
          kindCode: "04",
          num: "04452204180",
          createDate: "2020-07-17 00:00:00.0",
          closeDate: "",
          status: "открыт",
          openUfkCode: "4500",
          openUfkName:
            "Управление Федерального казначейства по Ленинградской области",
          openTofkName: "00130034",
          srvUfkCode: "4500",
          srvUfkName:
            "Управление Федерального казначейства по Ленинградской области",
          accountorgcode: "",
          accountorgfullname: "",
          ppocode: "",
          pponame: "",
          refopenUfkCode:
            "/epbs/registry/7710568760-TOFK/data?filtercode=00130034&filterstatus=ACTIVE&",
          refsrvUfkCode:
            "/epbs/registry/7710568760-TOFK/data?filtercode=-&filterstatus=ACTIVE&",
        },
      ],
      foAccounts: [
        {
          foName: "КОМИТЕТ ФИНАНСОВ ЛЕНИНГРАДСКОЙ ОБЛАСТИ",
          foCode: "40200015",
          accountTypeName: "Прямого ПБС",
          num: "03397949001",
        },
      ],
      participantPermissions: [
        {
          name: "Главного администратора доходов бюджета",
          code: "105",
          startDate: "2020-04-24 00:00:00.0",
          endDate: "",
        },
        {
          name: "Администратора доходов бюджета",
          code: "107",
          startDate: "2020-06-15 00:00:00.0",
          endDate: "",
        },
        {
          name: "Главного распорядителя бюджетных средств",
          code: "101",
          startDate: "2015-10-02 00:00:00.0",
          endDate: "",
        },
      ],
      nonParticipantPermissions: [],
      procurementPermissions: [
        {
          name: "заказчик",
          code: "201",
          startDate: "2016-08-01 00:00:00.0",
          endDate: "",
        },
        {
          name: "орган, устанавливающий требования к отдельным видам товаров, работ, услуг и (или) нормативные затраты",
          code: "210",
          startDate: "2020-04-24 00:00:00.0",
          endDate: "",
        },
        {
          name: "орган, размещающий правила нормирования",
          code: "209",
          startDate: "2020-04-24 00:00:00.0",
          endDate: "",
        },
      ],
      contacts: [
        {
          phone: "8 812 579 07 87; 8 812 579 07",
          site: "http://ombudsmanbiz.ru",
          mail: "lenobl@ombudsmanbiz.ru",
        },
      ],
      acceptAuths: [],
      transfauth: [],
      attachment: [],
      contracts: [],
      ubptransfauthbp: [],
      ubptransfauthbu: [],
      ubpfin: [],
      ksaccounts: [],
    },
  ],
  order: "id",
  orderDirection: "asc",
  limits: {},
  version: "10",
  pageCount: 33365,
};
